services:
  kibana:
    image: kibana:7.14.0
    container_name: kibana7
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
        - "5601:5601"        
    networks:
      - elastic
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: es7
    environment:
      - "cluster.name=es-docker-cluster"
      - "discovery.type=single-node"
#      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300      
    networks:
      - elastic
      
networks:
  elastic:
    driver: bridge      
