services:
    minio:
        image: minio/minio
        volumes:
            - './config:/root/.minio'
            - './data:/data'
        environment:
            - MINIO_ROOT_USER=admin
            - MINIO_ROOT_PASSWORD=admin123456
        container_name: minio
        ports:
            - '9090:9090'
            - '9000:9000'
        command: server /data --console-address ":9000" --address ":9090"
        # restart: always