services:
    redis:
        image: redis:6.0.6
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
            - ./conf/redis.conf:/etc/redis/redis.conf        
